name: daily-report

on:
  schedule:
    #- cron: '*/5 * * * *'
    - cron: '5,10,15,20,25,30,35,40,45,50,55,0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Scheduled Run
        run: echo "Scheduled workflow triggered at $(date)"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python send_email.py
        #comment