name: daily-report

on:
  #schedule:
    #- cron: '*/5 * * * *'
    #- cron: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Scheduled Run
        run: |
          echo "Scheduled workflow triggered at $(date)"
          echo "GitHub run ID: $GITHUB_RUN_ID"
          echo "GitHub trigger event: $GITHUB_EVENT_NAME"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run email code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python send_email.py
        #comment